---
- name: Check for local_project_dir pass in
  fail: msg="Playbook requires passed in local_project_dir"
  when: local_project_dir is not defined or not local_project_dir

- name: Run apt-get update
  command: apt-get update

- name: Install python3
  command: apt-get install python3 -y

- name: Create app directory
  file: 
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "{{ app_dir }}"
    - "{{ app_dir }}/config"
    - /var/log/rainfall-predictor

- name: Copy app dependency definition files and install script
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "{{ local_project_dir }}/requirements.txt", dest: "{{ app_dir }}", mode: '0644' }
    - { src: "{{ local_project_dir }}/requirements-intelpython.txt", dest: "{{ app_dir }}", mode: '0644' }
    - { src: "{{ local_project_dir }}/dockerconfig/install_IntelMKL.sh", dest: "{{ app_dir }}/config", mode: '0774' }

- name: Install special library for machine learning
  command: "{{ app_dir }}/config/install_IntelMKL.sh"

- name: Install app python dependencies
  command: pip install --no-cache-dir -r requirements.txt

- name: Install IntelPython library
  command: pip install --no-cache-dir -r requirements-intelpython.txt

- name: Copy core app code
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "{{ local_project_dir }}/build/*", dest: "{{ app_dir }}", mode: '0444' }
    - { src: "{{ local_project_dir }}/data/*", dest: "{{ app_dir }}/data", mode: '0444' }
    - { src: "{{ local_project_dir }}/VERSION", dest: "{{ app_dir }}", mode: '0444' }

- name: Create executable inside /usr/bin
  command: |
    chmod +x "{{ app_dir }}/main.py"
    ln -s "{{ app_dir }}/main.py" /usr/bin/rainfall-predictor

- name: Build system daemon user
  command: >
    useradd --system --no-user-group --gid daemon
            --create-home --home-dir "/var/cache/rainfall-predictor"
            rainfalld

- name: Enable log location for daemon
  command: chown rainfalld "/var/log/rainfall-predictor"

- name: Cleanup installation
  command: rm -rf "{{ app_dir }}/config"
