---
# configure
- name: Build system daemon user
  command: >
    useradd --user-group --groups sudo --create-home
            --comment "Administrator"
            admin

- name: Generate password hash locally
  delegate_to: localhost                # run on local workstation instead of remote
  vars_files:
    - ../../bin/secrets.yml
  expect:
    command: echo {{ admin_secret }} | shasum -a 512 | awk -F " " '{print $1}'
    register: password_hash

- name: Set Admin password on remote
  become: true
  user:
    name: admin
    password: "{{ password_hash.stdout_lines[-1] }}"
