---
# rainfall-predictor-ansible
- become: yes
  block:
    - name: Install Rainfall Predictor app
      hosts: gce_instances_ips
      become_user: root
      become_method: sudo
      roles:
        - install
        - configure
        
    - name: Deploy Rainfall Predictor app
      hosts: gce_instances_ips
      become_user: root
      become_method: sudo
      roles:
        - run
